### ISSUE TITLE
更新最新，路径修复的按钮依然显示不出

### ISSUE THREAD

**Issue by vjoo** [juehackr/comfyui_fk_server#21]
自从更新了comfyui2.3就不行了，不知道和什么有冲突，那个“show image feed”也关不掉，是不是被重叠了，插件删掉重装了8月更新的也不行
![screenshot_2024-10-15_10-47-13](https://github.com/user-attachments/assets/e58d401e-2eef-4601-a886-4288647f0ffd)

**Comment by juehackr** [comment]
感谢反馈，下版修复

**Comment by juehackr** [comment]
更新了~
